import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar  from '../components/Navbar'

export default function Home() {
  return (
    <div className="bg-customBlue h-screen">
      <Head>
        <title>Embr</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <main style={styles}>
      <div className='flex justify-center w-screen h-8 bg-customWarning '> 
        
        <p className='text-embrWhite text-sm pt-2'>Our exclusive presale will begin on the 16th of August 2021. To find out if you are eligible <a className='text-embrOrange underline' href=''> click here</a></p> 
     
      </div>
      <Navbar />
      </main>

     
    </div>
  )
}
