import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Banner from '../components/Banner'
import Navbar  from '../components/Navbar'
import EligibilityCheckerPage from '../components/EligibilityCheckerPage'
import CertikBanner from '../components/CertikBanner'

export default function Home() {
  return (
    <div className="sm:h-screen">
      <Head>
        <title>Embr</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css"></link>
      </Head>

      
      <main className=''>
        <div className='bg-gradient-to-r from-customGrey to-customBlue pb-20'>
        <div className='block  h-10'>
        <Banner />
        </div>
        <div className='block h-20'>
          <Navbar />
        </div>
     
     <EligibilityCheckerPage />
        </div>
        <CertikBanner />
   
      </main>

     
    </div>
  )
}
